"""autogenerated

Revision ID: 2ed73881770d
Revises: 8606fa83a998
Create Date: 2025-11-01 18:47:55.029559

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2ed73881770d"
down_revision = "8606fa83a998"
branch_labels = None
depends_on = None


def upgrade() -> None:
    dialect_name = op.get_bind().dialect.name
    if dialect_name == "mssql":
        timestamp_column = sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=False,
            server_default=sa.text("SYSUTCDATETIME()"),
        )
    else:
        timestamp_column = sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            nullable=False,
            server_default=sa.text("CURRENT_TIMESTAMP"),
        )

    op.create_table(
        "workspace_permissions",
        sa.Column("workspace_name", sa.String(length=63), nullable=False),
        sa.Column("username", sa.String(length=255), nullable=False),
        sa.Column("resource_type", sa.String(length=64), nullable=False),
        sa.Column("permission", sa.String(length=32), nullable=False),
        timestamp_column,
        sa.PrimaryKeyConstraint(
            "workspace_name", "username", "resource_type", name="workspace_permissions_pk"
        ),
    )
    op.create_index(
        "idx_workspace_permissions_username", "workspace_permissions", ["username"], unique=False
    )
    op.create_index(
        "idx_workspace_permissions_workspace",
        "workspace_permissions",
        ["workspace_name"],
        unique=False,
    )

    with op.batch_alter_table("registered_model_permissions", recreate="auto") as batch_op:
        batch_op.add_column(
            sa.Column(
                "workspace",
                sa.String(length=63),
                nullable=True,
            )
        )

    registered_model_permissions = sa.table(
        "registered_model_permissions",
        sa.column("workspace", sa.String(length=63)),
    )
    conn = op.get_bind()
    conn.execute(
        registered_model_permissions.update()
        .where(registered_model_permissions.c.workspace.is_(None))
        .values(workspace="default")
    )

    with op.batch_alter_table("registered_model_permissions", recreate="auto") as batch_op:
        batch_op.alter_column(
            "workspace",
            existing_type=sa.String(length=63),
            nullable=False,
        )
        batch_op.drop_constraint("unique_name_user", type_="unique")
        batch_op.create_unique_constraint(
            "unique_workspace_name_user", ["workspace", "name", "user_id"]
        )


def downgrade() -> None:
    conn = op.get_bind()
    conflicts = conn.execute(
        sa.text(
            """
            SELECT name, user_id, COUNT(DISTINCT workspace) AS workspace_count
            FROM registered_model_permissions
            GROUP BY name, user_id
            HAVING COUNT(DISTINCT workspace) > 1
            """
        )
    ).fetchall()
    if conflicts:
        details = ", ".join(f"(name={row.name}, user_id={row.user_id})" for row in conflicts)
        raise RuntimeError(
            "Cannot downgrade workspace permissions migration because dropping the workspace "
            + "column would create conflicts for the following registered_model_permissions rows: "
            f"{details}. Please merge or delete the conflicting rows before retrying the downgrade."
        )

    op.drop_index("idx_workspace_permissions_workspace", table_name="workspace_permissions")
    op.drop_index("idx_workspace_permissions_username", table_name="workspace_permissions")
    op.drop_table("workspace_permissions")
    with op.batch_alter_table("registered_model_permissions", recreate="auto") as batch_op:
        batch_op.drop_constraint("unique_workspace_name_user", type_="unique")
        batch_op.create_unique_constraint("unique_name_user", ["name", "user_id"])
        batch_op.drop_column("workspace")
