# Build a wheel for MLflow and upload it as an artifact.
name: build-wheel

on:
  push:
    branches:
      - master
      - branch-[0-9]+.[0-9]+
      - main
      - rhoai-*
  pull_request:
    paths-ignore:
      - "docs/**"
      - "**.md"
      - "dev/clint/**"
